[tool.poetry]
<<<<<<< Updated upstream
name = "netbox-dns"
version = "0.17.0"
description = "Netbox Dns is a netbox plugin for managing zone, nameserver and record inventory."
=======
name = "netbox-plugin-dns"
version = "0.18.0-beta2"
description = "Netbox DNS is a netbox plugin for managing DNS inventory"
authors = ["Peter Eckel <pe-netbox-dns@hindenburgring.com>"]
homepage = "https://github.com/peteeckel/netbox-plugin-dns"
repository = "https://github.com/peteeckel/netbox-plugin-dns"
license = "MIT"
>>>>>>> Stashed changes
readme = "README.md"
homepage = "https://github.com/auroraresearchlab/netbox-dns"
repository = "https://github.com/auroraresearchlab/netbox-dns"
authors = ["Aurora Research Lab <info@auroraresearchlab.com>"]
license = "MIT"
include = ["netbox_dns/templates/*"]
exclude = ["netbox_dns/tests/*"]
keywords = ["netbox", "netbox-plugin", "dns"]

[tool.poetry.dependencies]
python = "^3.8"
dnspython = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = { version = "^21.8b0", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
